### PR TITLE
Add callbacks to listenForCode/createServer function

### PR DESCRIPTION
**Pull request by dommilosz**
See #20

### CODE REVIEW

**Comment by dommilosz** [comment]
I think the onstart callback location doesn't really matter that much. I merged your changes.

**Comment by CordonZeus22** [comment]
If the server can't start, for example the port is already in use, put the call of `onstart` after the call of `listen` will call `onstart`, but put `onstart` in the callback of `listen` will not call it. You can try with

```js
import http from "http";

const server1 = http.createServer();
const server2 = http.createServer();

server1.listen(10, "localhost", function() {
    console.log("Server 1 started. Listen callback.");
});

console.log("Server 1 started.");

server2.listen(10, "localhost", function() {
    console.log("Server 2 started. Listen callback.");
});

console.log("Server 2 started.");
```

**Comment by dommilosz** [comment]
Try wrapping everything in async function and await the listens as is the
case in library code

**Comment by CordonZeus22** [comment]
It doesn't change anything because the `listen` method doesn't return a `Promise`. I just tried to be sure.

**Comment by dommilosz** [comment]
Okay. I see I might've used it as express webserwer in that listen actually returns promise. I've added test for that and handling errors generated by the server.

**Comment by CordonZeus22** [comment]
The `createServer` function now returns a `Promise` that resolves when the server close or rejects when an error occurred. I think you want to put the resolve in the `listen` callback because the `listenForCode` function await the `createServer` function.

**Comment by dommilosz** [comment]
Yeah good point. Only if I had ran all the tests

**Comment by CordonZeus22** [comment]
Also I think the `createServer` needs to return the server not `undefined`. It's better to not use `any`, use `unknown` if any type can be accepted.

**Comment by CordonZeus22** [comment]
Why also returns the server when the server closes ?

**Comment by dommilosz** [comment]
Do you have any more suggestions or can I merge?

**Comment by CordonZeus22** [comment]
I think it's ok for me, you can merge. One thing maybe, when you update the `package.json` run `npm i` for also update the `package-lock.json`

**Pull request merged**
